### ISSUE TITLE
crash on 2.0.6

### ISSUE THREAD

**Issue by winsrp** [MrRiegel/Storage-Network#109]
Crash upon loading map and opening the request table.

`// Oh - I know what I did wrong!

Time: 11/27/16 8:26 AM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at mrriegel.storagenetwork.container.ContainerAbstractRequest.func_75145_c(ContainerAbstractRequest.java:206)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:235)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mrriegel.storagenetwork.container.ContainerAbstractRequest.func_75145_c(ContainerAbstractRequest.java:206)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:235)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 263
	Entity Name: winsrp
	Entity's Exact location: 114.72, 65.00, 188.21
	Entity's Block location: World: (114,65,188), Chunk: (at 2,4,12 in 7,11; contains blocks 112,0,176 to 127,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@4b961eb5
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by KidsDontPlay** [comment]
I can't reproduce the crash.
Can you break the request table, place it and open the GUI again?

**Comment by winsrp** [comment]
I would love to try but i won't let me into the Game due to error

**Comment by winsrp** [comment]
allow me to direct you a little bit, cust it would be great for you to have the bug fixed. I was using immersive engineering mod, and I setup a silo (there is an item named the engineers manual that explains how to build a silo, and a silo, is well... a huge container of items of a single item type, but instead of having input/out on any side, it has input from above, and output from below.

So I setup a network, hook up some normal chests, and then I hooked the silo by having a network export on top of the silo, so I can put items in, and a network storage so I could read and extract from the silo on demand, and things went all downhill from there.

The items on the silo around (500+ at the moment) were read from the request table but instead of reading 500+ it read like 56, when I tried pulling the silo items out from the request table to my inventory instead of taking a stack out, it took only one, and the number 56 never went down, and when I tried putting items in.. it broke, hell went lose and yada yada.... so no idea how to hook the silo to the network so I can read the items in the request table and my game is stuck now with that error.

**Comment by KidsDontPlay** [comment]
for that problem you should open another issue and post the crash log there.
To enter your world you can enable 'STOPTICK' in the config file, break the devices on the silo and disable 'STOPTICK'

**Comment by winsrp** [comment]
I'm actually talking about the same thing, that is the error log for the story I posted. I will try to get into my world using the method you told me about.

**Comment by KidsDontPlay** [comment]
the error log you posted before could only occur if the request table GUI is open. So it should be easy to enter the world and break the device.
The silo is not compatible the the storage device. It's up to IE to make it compatible but I guess that won't happen. Refined storage has the same problem with the silo.

**Comment by winsrp** [comment]
too bad, I really like the silo as the big container for my server, instead of something like iron chests.
