### ISSUE TITLE
testing fluids, got a little crash

### ISSUE THREAD

**Issue by winsrp** [MrRiegel/Storage-Network#25]
using version 1.8.9 - 1.8.0

I had a fluid import block (red one) and I removed a block that was attached to it and the replaced that block with another which should not have a connection and it crashed.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCoreMod (movingworld-MC1.8.9-INDEV-H-full.jar)
  CorePlugin (Fluxed Redstone-1.3.0.31.jar)
  BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.3.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-38.jar)
  AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 3/16/16 11:20 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at mrriegel.storagenetwork.tile.TileMaster.fimpor(TileMaster.java:762)
    at mrriegel.storagenetwork.tile.TileMaster.func_73660_a(TileMaster.java:1066)
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:250)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at mrriegel.storagenetwork.tile.TileMaster.fimpor(TileMaster.java:762)
    at mrriegel.storagenetwork.tile.TileMaster.func_73660_a(TileMaster.java:1066)

-- Block entity being ticked --
Details:
    Name: tileMaster // mrriegel.storagenetwork.tile.TileMaster
    Block type: ID #728 (tile.storagenetwork:master // mrriegel.storagenetwork.blocks.BlockMaster)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (24,64,69), Chunk: (at 8,4,5 in 1,4; contains blocks 16,0,64 to 31,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Actual block type: ID #728 (tile.storagenetwork:master // mrriegel.storagenetwork.blocks.BlockMaster)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)

-- Affected level --
Details:
    Level name: Brand new world
    All players: 1 total; [EntityPlayerMP['winsrp'/4838140, l='Brand new world', x=29.46, y=68.69, z=72.42]]
    Chunk stats: ServerChunkCache: 1190 Drop: 0
    Level seed: 3239291013610220986
    Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
    Level generator options: {"landScheme":"archipelago","tempScheme":"small_zones","rainScheme":"medium_zones","biomeSize":"small","amplitude":1.0,"generateBopOre":true,"generateBopSoils":true,"generateBopTrees":true,"generateBopGrasses":true,"generateBopFoliage":true,"generateBopFlowers":true,"generateBopPlants":true,"generateBopWaterPlants":true,"generateBopMushrooms":true,"generateRockFormations":true,"generatePoisonIvy":true,"generateFlax":true,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateNetherPlants":true,"generateEndFeatures":true}
    Level spawn location: 48.00,64.00,168.00 - World: (48,64,168), Chunk: (at 0,4,8 in 3,10; contains blocks 48,0,160 to 63,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 593630 game time, 6191 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: true. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:250)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    CPU: 8x Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 420293752 bytes (400 MB) / 3237613568 bytes (3087 MB) up to 4281597952 bytes (4083 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 66
    FML: MCP 9.19 Powered by Forge 11.15.1.1762 Optifine OptiFine_1.8.9_HD_U_H4_pre 50 mods loaded, 50 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAAAAAAAAAAAA mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAAAAAAAAAAAA FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1762.jar) 
    UCHIJAAAAAAAAAAAAAA Forge{11.15.1.1762} [Minecraft Forge] (forge-1.8.9-11.15.1.1762.jar) 
    UCHIJAAAAAAAAAAAAAA darkevilmac.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
    UCHIJAAAAAAAAAAAAAA AppleCore{1.3.0} [AppleCore] (AppleCore-mc1.8.9-1.3.0.jar) 
    UCHIJAAAAAAAAAAAAAA MovingWorld{MC1.8.9-INDEV-H} [Moving World] (movingworld-MC1.8.9-INDEV-H-full.jar) 
    UCHIJAAAAAAAAAAAAAA ArchimedesShipsPlus{MC1.8.9-INDEV-G} [Archimedes' Ships Plus] (archimedesshipsplus-MC1.8.9-INDEV-G.jar) 
    UCHIJAAAAAAAAAAAAAA ArchitectureCraft{1.3.1} [ArchitectureCraft] (ArchitectureCraft-1.3.1-mc1.8.9.jar) 
    UCHIJAAAAAAAAAAAAAA bdlib{1.10.0.30} [BD Lib] (bdlib-1.10.0.30-mc1.8.9.jar) 
    UCHIJAAAAAAAAAAAAAA BetterAchievements{0.1.1} [Better Achievements] (BetterAchievements-1.8.9-0.1.1.jar) 
    UCHIJAAAAAAAAAAAAAA BetterFoliage{2.0.3} [Better Foliage] (BetterFoliage-MC1.8.x-2.0.3.jar) 
    UCHIJAAAAAAAAAAAAAA BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1926-universal.jar) 
    UCHIJAAAAAAAAAAAAAA bookshelfapi{2.3.6} [Bookshelf] (Bookshelf-API-1.8.9-2.3.6.jar) 
    UCHIJAAAAAAAAAAAAAA caterpillar{0.0.0} [Caterpillar] (Caterpillar-1.2.189b76.jar) 
    UCHIJAAAAAAAAAAAAAA cfmce{1.0} [MrCrayfish's Furniture Mod: Community Edition] (cfmce-1.0-mc1.8.9.jar) 
    UCHIJAAAAAAAAAAAAAA Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
    UCHIJAAAAAAAAAAAAAA EnderZoo{1.8.9-1.1.3.35} [Ender Zoo] (EnderZoo-1.8.9-1.1.3.35.jar) 
    UCHIJAAAAAAAAAAAAAA mcmultipart{1.0.8} [MCMultiPart] (MCMultiPart-1.0.8-universal.jar) 
    UCHIJAAAAAAAAAAAAAA reborncore{1.4.3.20} [RebornCore] (RebornCore-1.8.9-1.4.3.20-universal.jar) 
    UCHIJAAAAAAAAAAAAAA fluxedredstone{1.3.0.31} [FluxedRedstone] (Fluxed Redstone-1.3.0.31.jar) 
    UCHIJAAAAAAAAAAAAAA substratum{1.1.0.1} [Substratum] (Substratum-1.8.9-1.1.0.1.jar) 
    UCHIJAAAAAAAAAAAAAA foundry{1.4.0.0} [Foundry] (Foundry-1.8.9-1.4.0.0.jar) 
    UCHIJAAAAAAAAAAAAAA furnus{1.72} [Furnus] (Furnus-1.8.9-1.72.jar) 
    UCHIJAAAAAAAAAAAAAA pressure{1.3.0.22} [Pressure Pipes] (pressure-1.3.0.22-mc1.8.9.jar) 
    UCHIJAAAAAAAAAAAAAA advgenerators{0.9.19.8} [Advanced Generators] (generators-0.9.19.8-mc1.8.9.jar) 
    UCHIJAAAAAAAAAAAAAA inventorytweaks{1.60-beta-38-b8950ce} [Inventory Tweaks] (InventoryTweaks-1.60-beta-38.jar) 
    UCHIJAAAAAAAAAAAAAA ironbackpacks{1.8-1.0.7} [Iron Backpacks] (IronBackpacks-1.8-1.0.7.jar) 
    UCHIJAAAAAAAAAAAAAA IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAAAAAAAAAAAAAA JEI{2.28.5.172} [Just Enough Items] (jei_1.8.9-2.28.5.172.jar) 
    UCHIJAAAAAAAAAAAAAA journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
    UCHIJAAAAAAAAAAAAAA RadixCore{1.8.9-2.1.0} [RadixCore] (RadixCore-1.8.9-2.1.0-universal.jar) 
    UCHIJAAAAAAAAAAAAAA MCA{1.8.9-5.1.1.2} [Minecraft Comes Alive] (MCA-1.8.9-5.1.1.2-universal.jar) 
    UCHIJAAAAAAAAAAAAAA MissingRecipies{0.1.0} [MissingRecipies] (Missing Recipes 0.1.jar) 
    UCHIJAAAAAAAAAAAAAA MoreFurnaces{1.5.0} [More Furnaces] (MoreFurnaces-1.5.0-MC1.8.9.jar) 
    UCHIJAAAAAAAAAAAAAA cfm{3.6} [MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.6.1(1.8.9).jar) 
    UCHIJAAAAAAAAAAAAAA neotech{2.4.1} [NeoTech] (NeoTech-1.8.9-2.4.1.jar) 
    UCHIJAAAAAAAAAAAAAA fodc{1.7.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.2.jar) 
    UCHIJAAAAAAAAAAAAAA practicalities{2.0.0-b6} [Practicalities] (practicalities-1.8.9-2.0.0-b6.jar) 
    UCHIJAAAAAAAAAAAAAA progressiveautomation{1.6.35} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.35.jar) 
    UCHIJAAAAAAAAAAAAAA redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2.jar) 
    UCHIJAAAAAAAAAAAAAA rftools{4.23beta32} [RFTools] (rftools-1.8.9-4.23beta32.jar) 
    UCHIJAAAAAAAAAAAAAA Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
    UCHIJAAAAAAAAAAAAAA wuppy29_simplerecipes{1.9.0} [Simple Recipes] (Simple Recipes 1.8.0-1.9.0.jar) 
    UCHIJAAAAAAAAAAAAAA SpiceOfLife{1.3.1} [The Spice of Life] (SpiceOfLife-mc1.8.9-1.3.1.jar) 
    UCHIJAAAAAAAAAAAAAA StorageDrawers{1.8.9-2.4.4} [Storage Drawers] (StorageDrawers-1.8.9-2.4.4.jar) 
    UCHIJAAAAAAAAAAAAAA storagenetwork{1.8.0} [Storage Network] (StorageNetwork-1.8.9-1.8.0.jar) 
    UCHIJAAAAAAAAAAAAAA usefulrecipes{1.1} [UsefulRecipes] (UsefulRecipes-1.1.0(1.8.9).jar) 
    UCHIJAAAAAAAAAAAAAA usefulstones{0.2} [Useful Stones] (UsefulStones_0.2-MCv1.8.9.jar) 
    UCHIJAAAAAAAAAAAAAA Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJAAAAAAAAAAAAAA wawla{1.4.7} [What Are We Looking At] (Wawla-1.4.7-1.8+.jar) 
    Loaded coremods (and transformers): 
MovingWorldCoreMod (movingworld-MC1.8.9-INDEV-H-full.jar)

CorePlugin (Fluxed Redstone-1.3.0.31.jar)

BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.3.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
FMLPlugin (InventoryTweaks-1.60-beta-38.jar)
  invtweaks.forge.asm.ContainerTransformer
AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    List of loaded APIs: 
        * AppleCoreAPI (2.0.0) from AppleCore-mc1.8.9-1.3.0.jar
        * BetterAchievements|API (0.1.1) from BetterAchievements-1.8.9-0.1.1.jar
        * CoFHAPI (1.8.9R1.2.0B1) from RebornCore-1.8.9-1.4.3.20-universal.jar
        * CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
        * CoFHAPI|energy (1.8.9R1.2.0B1) from StorageNetwork-1.8.9-1.8.0.jar
        * CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
        * foundry.api (1.4.0.0) from Foundry-1.8.9-1.4.0.0.jar
        * JustEnoughItemsAPI (3.1.0) from jei_1.8.9-2.28.5.172.jar
        * McJtyLib (1.8.9-1.8.1beta8) from mcjtylib-1.8.9-1.8.1beta8.jar
        * pressureAPI (1.3.0.22) from pressure-1.3.0.22-mc1.8.9.jar
        * reborncoreAPI (1.4.3.20) from RebornCore-1.8.9-1.4.3.20-universal.jar
        * StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        * StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        * StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        * StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        * StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        * StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        * StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        * StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        * StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
        * WailaAPI (1.3) from Waila-1.6.0-B3_1.8.8.jar
    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['winsrp'/4838140, l='Brand new world', x=29.46, y=68.69, z=72.42]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    OptiFine Version: OptiFine_1.8.9_HD_U_H4_pre
    Render Distance Chunks: 16
    Mipmaps: 4
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    Shaders: KUDA-Shaders v6.1.13 BETA - Ultra.zip
    OpenGlVersion: 4.5.0 NVIDIA 358.91
    OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
    OpenGlVendor: NVIDIA Corporation
    CpuCount: 8
```

**Comment by KidsDontPlay** [comment]
I absolutely cannot understand why this happen.
Can you reproduce the crash?
What tank do you use?

**Comment by winsrp** [comment]
yeah I can reproduce it, it wont let me into the game anymore actually, same error on the same map.

Was using the connection with a fluid outlet from the advanced generators mods, it's a multiblock structure, so I took it off, (because it was not pulling syngas out of the syngas generator) and then I put a water pump from the pressure pipes mod to see if the pump was going to help, the second I put the pump... crash

**Comment by winsrp** [comment]
it is also to note that your block was on the north side because the outlet has 6 available sides, but when I put the pump it went from west to east, and your plug was still on north.. I was going to move it, but crash happens.

**Comment by KidsDontPlay** [comment]
good news: It won't crash anymore
bad news: I don't know why you cannot pump fluid out of the outlet. the mod is written in scala and I am clueless about scala.

**Comment by winsrp** [comment]
great!, I think the issue is that those generators need to find a specific interface in your pipes for it to be able to detect a connection and give you liquids.

For power he had the same issue, he needed some class IEnergyConnection to be implemented to detect that it was a power pipe. I guess there is some similar class like IFluidConnection? that he needs implemented to detect the fuild pipe...

**Comment by winsrp** [comment]
I could ask the guy from that mod for you, but if you ask him yourself you guys might be able to understand each other better, he is very friendly. Ask him what he needed from a fluid connection to be detected.

**Comment by winsrp** [comment]
btw how do I install the fix? I still can't get into my world.

**Comment by KidsDontPlay** [comment]
https://github.com/bdew/pressure/issues/64
