### ISSUE TITLE
[SERVER] [CRASH] java.lang.NoSuchMethodError: .../minecraft/creativetab/CreativeTabs

### ISSUE THREAD

**Issue by wMaestro** [MrRiegel/Storage-Network#40]
Upon loading a custom modpack using this and a few other 1.8.9 mods, I receive the following fatal crash, which seems to indicate you're calling a client-side method on the dedicated server running this mod. (Very similar to [this issue with another mod](https://github.com/coolAlias/ZeldaSwordSkills/issues/42), if that helps any.) Not quite sure why it isn't reported elsewhere, or what may be causing this issue in this pack.

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
>   MalisisCorePlugin (malisiscore-1.8.9-2.1.6.jar)
>   IC2core (industrialcraft-2-2.3.247-ex18.jar)
>   LoadingPlugin (FastLeaveDecay-1.2.jar)
>   LoadingPlugin (HardcoreDarkness-MC1.8.8-1.8.jar)
>   LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
> Contact their authors BEFORE contacting forge
> 
> // Sorry :(
> 
> Time: 5/19/16 6:09 AM
> Description: Exception in server tick loop
> 
> net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.item.Item.func_77640_w()Lnet/minecraft/creativetab/CreativeTabs;
>   at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
>   at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
>   at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
>   at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:325)
>   at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:205)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
>   at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NoSuchMethodError: net.minecraft.item.Item.func_77640_w()Lnet/minecraft/creativetab/CreativeTabs;
>   at mrriegel.storagenetwork.helper.Util.init(Util.java:47)
>   at mrriegel.storagenetwork.proxy.CommonProxy.postInit(CommonProxy.java:32)
>   at mrriegel.storagenetwork.StorageNetwork.postInit(StorageNetwork.java:65)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:497)
>   at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
>   at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:497)
>   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>   at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
>   at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:497)
>   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>   at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
>   at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
>   ... 5 more
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> -- System Details --
> Details:
>   Minecraft Version: 1.8.9
>   Operating System: Linux (amd64) version 2.6.32-431.el6.x86_64
>   Java Version: 1.8.0_40, Oracle Corporation
>   Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
>   Memory: 3397556152 bytes (3240 MB) / 3952607232 bytes (3769 MB) up to 3952607232 bytes (3769 MB)
>   JVM Flags: 3 total; -Xmx4096M -Xms4096M -XX:MaxPermSize=256m
>   IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
>   FML: MCP 9.19 Powered by Forge 11.15.1.1875 43 mods loaded, 43 mods active
>   States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
>   UCHIJ   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
>   UCHIJ   FML{8.0.99.99} [Forge Mod Loader](custom.jar) 
>   UCHIJ   Forge{11.15.1.1875} [Minecraft Forge](custom.jar) 
>   UCHIJ   archmagus{0.8.0} [Archmagus](Archmagus-1.8.9-0.8.0.jar) 
>   UCHIJ   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
>   UCHIJ   aura{592} [Aura Cascade](AuraCascade-592.jar) 
>   UCHIJ   BiomesOPlenty{3.0.0} [Biomes O' Plenty](BiomesOPlenty-1.8.9-3.0.0.2004-universal.jar) 
>   UCHIJ   BloodMagic{1.8.9-2.0.0-20} [Blood Magic: Alchemical Wizardry](BloodMagic-1.8.9-2.0.0-20.jar) 
>   UCHIJ   BuildCraft|Core{7.2.6} [BuildCraft](buildcraft-7.2.6.jar) 
>   UCHIJ   BuildCraft|Silicon{7.2.6} [BC Silicon](buildcraft-7.2.6.jar) 
>   UCHIJ   BuildCraft|Transport{7.2.6} [BC Transport](buildcraft-7.2.6.jar) 
>   UCHIJ   BuildCraft|Builders{7.2.6} [BC Builders](buildcraft-7.2.6.jar) 
>   UCHIJ   BuildCraft|Energy{7.2.6} [BC Energy](buildcraft-7.2.6.jar) 
>   UCHIJ   BuildCraft|Robotics{7.2.6} [BC Robotics](buildcraft-7.2.6.jar) 
>   UCHIJ   BuildCraft|Factory{7.2.6} [BC Factory](buildcraft-7.2.6.jar) 
>   UCHIJ   Chameleon{1.8.9-1.1.2} [Chameleon](Chameleon-1.8.9-1.1.2.jar) 
>   UCHIJ   chisel{@VERSION@} [Chisel](Chisel-MC1.8.9-0.0.2.6.jar) 
>   UCHIJ   ComputerCraft{1.78} [ComputerCraft](ComputerCraft1.78.jar) 
>   UCHIJ   FastLeaveDecay{1.1} [Fast Leave Decay](FastLeaveDecay-1.2.jar) 
>   UCHIJ   GraveStone{1.0.0} [GraveStone](GraveStone-1.8.9-Graves-1.0.0.jar) 
>   UCHIJ   HardcoreDarkness{1.8} [Hardcore Darkness](HardcoreDarkness-MC1.8.8-1.8.jar) 
>   UCHIJ   mantle{1.8.9-0.9.2.jenkins102} [Mantle](Mantle-1.8.9-0.9.2.jar) 
>   UCHIJ   tconstruct{1.8.9-2.2.1.jenkins1005} [Tinkers' Construct](TConstruct-1.8.9-2.2.1.jar) 
>   UCHIJ   ImmersiveEngineering{0.8-26} [Immersive Engineering](ImmersiveEngineering-0.8-26.jar) 
>   UCHIJ   IC2{2.3.247-ex18} [IndustrialCraft 2](industrialcraft-2-2.3.247-ex18.jar) 
>   UCHIJ   InfernalMobs{1.6.6} [Infernal Mobs](InfernalMobs-1.8.8.jar) 
>   UCHIJ   IronChest{6.0.125.770} [Iron Chest](ironchest-1.8.9-6.0.125.770.jar) 
>   UCHIJ   lucky{7.0.2} [Lucky Block](LuckyBlock_1-8-9_v7-0-2.zip) 
>   UCHIJ   malisiscore{1.8.9-2.1.6} [MalisisCore](malisiscore-1.8.9-2.1.6.jar) 
>   UCHIJ   malisisdoors{1.8.9-3.1.4} [MalisisDoors](malisisdoors-1.8.9-3.1.4.jar) 
>   UCHIJ   testdummy{1.0} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.9b.jar) 
>   UCHIJ   progressiveautomation{1.6.44} [Progressive Automation](ProgressiveAutomation-1.8.9-1.6.44.jar) 
>   UCHIJ   ProjectE{1.8.9-PE1.1.4} [ProjectE](ProjectE-1.8.9-PE1.1.4.jar) 
>   UCHIJ   Psi{beta-23} [Psi](Psi-beta-23.jar) 
>   UCHIJ   quantumflux{2.0.1} [QuantumFlux](quantumflux-1.8.9-2.0.1.jar) 
>   UCHIJ   randomthings{3.6.6} [Random Things](RandomThings-MC1.8.9-3.6.6.jar) 
>   UCHIJ   SoulShardsTOW{1.8.9-2.2.8-16} [Soul Shards - The Old Ways](SoulShards-TOW-1.8.9-2.2.8-16.jar) 
>   UCHIJ   StorageDrawers{1.8.9-2.6.4} [Storage Drawers](StorageDrawers-1.8.9-2.6.4.jar) 
>   UCHIE   storagenetwork{1.10.0} [Storage Network](StorageNetwork-1.8.9-1.10.0.jar) 
>   UCHIJ   Thaumcraft{5.2.4} [Thaumcraft](Thaumcraft-1.8.9-5.2.4.jar) 
>   UCHIJ   Waila{1.6.0} [Waila](Waila-1.6.0-B3_1.8.8.jar) 
>   UCHIJ   YALSM{2.1.5} [Yet Another Leather Smelting Mod](yalsm-2.1.5-mc1.8.9.jar) 
>   UCHIJ   denseores{1.0} [denseores](denseores-1.8-alpha-2.0.3.jar) 
>   Loaded coremods (and transformers): 
> ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
> 
> MalisisCorePlugin (malisiscore-1.8.9-2.1.6.jar)
>   net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
>   net.malisis.core.util.chunkblock.ChunkBlockTransformer
>   net.malisis.core.renderer.transformer.MalisisRendererTransformer
>   net.malisis.core.renderer.icon.asm.TextureMapTransformer
> IC2core (industrialcraft-2-2.3.247-ex18.jar)
> 
> LoadingPlugin (FastLeaveDecay-1.2.jar)
>   lumien.fastleavedecay.asm.ClassTransformer
> LoadingPlugin (HardcoreDarkness-MC1.8.8-1.8.jar)
>   lumien.hardcoredarkness.asm.ClassTransformer
> LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
>   lumien.randomthings.asm.ClassTransformer
>   Pulsar/tconstruct loaded Pulses: 
>       - TinkerCommons (Enabled/Forced)
>       - TinkerWorld (Enabled/Not Forced)
>       - TinkerTools (Enabled/Not Forced)
>       - TinkerSmeltery (Enabled/Not Forced)
>       - TinkerGadgets (Enabled/Not Forced)
>       - TinkerOredict (Enabled/Forced)
>       - TinkerIntegration (Enabled/Forced)
>       - TinkerFluids (Enabled/Forced)
>       - TinkerMaterials (Enabled/Forced)
> 
>   Profiler Position: N/A (disabled)
>   Is Modded: Definitely; Server brand changed to 'fml,forge'
>   Type: Dedicated Server (map_server.txt)

**Comment by wMaestro** [comment]
In case this gets noticed, the crash doesn't occur if I downgrade to Storage Network v1.9.2 so it's most likely caused by a commit that occurred between that version and the one I used originally (v1.10.0).

**Comment by wMaestro** [comment]
Thanks Riegel!
