### ISSUE TITLE
Compatibility issue with recent JEI versions

### ISSUE THREAD

**Issue by Entoarox** [MrRiegel/Storage-Network#7]
```
java.lang.NoSuchMethodError: mezz.jei.gui.ingredients.GuiIngredient.getAll()Ljava/util/List;
    at mrriegel.storagenetwork.jei.RecipeTransferHandler.transferRecipe(RecipeTransferHandler.java:57)
    at mezz.jei.transfer.RecipeTransferUtil.transferRecipe(RecipeTransferUtil.java:36)
    at mezz.jei.transfer.RecipeTransferUtil.transferRecipe(RecipeTransferUtil.java:21)
    at mezz.jei.gui.RecipesGui.func_146284_a(RecipesGui.java:319)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:466)
    at mezz.jei.gui.RecipesGui.func_73864_a(RecipesGui.java:247)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
    at mezz.jei.gui.RecipesGui.func_146274_d(RecipesGui.java:223)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Happens whenever a player tries to insert a crafting recipe into the request table.

**Comment by KidsDontPlay** [comment]
thats a problem with the new JEI.
you could use an older version of JEI until I release a new version
I recommend jei_1.8.9-2.25.4.139.jar

**Comment by mezz** [comment]
Before, custom recipe transfer handlers required using some of JEI's internal classes. Now it is done using only the API, so I shouldn't break your recipe transfer handler by accident again.

**Comment by MrGraphic** [comment]
Just an info, as of 1.5 it works again.

**Comment by KidsDontPlay** [comment]
You're right. I forgot to close
